FROM sorintlab/stolon:v0.6.0-pg9.6

ARG pubkey
ARG privkey

COPY $pubkey /root/.ssh/authorized_keys
COPY $privkey /root/.ssh/
RUN chmod 400 /root/.ssh/*

ENV STKEEPER_CLUSTER_NAME=stolon-cluster \
    STKEEPER_STORE_BACKEND=etcd \
    STKEEPER_STORE_ENDPOINTS=http://localhost:2379 \
    STKEEPER_DATA_DIR=/data/postgres

RUN mkdir -p ${STKEEPER_DATA_DIR} && \
    chmod 700 ${STKEEPER_DATA_DIR} && \
    chown postgres -R ${STKEEPER_DATA_DIR}
VOLUME ["${STKEEPER_DATA_DIR}"]

COPY bin/keeper-entrypoint.sh /usr/local/bin/
RUN chmod 777 /usr/local/bin/keeper-entrypoint.sh

RUN apt-get update && apt-get install -y bash curl gawk locales-all netcat-openbsd rsync ssh sudo && \
    chsh -s /bin/bash && mkdir /var/run/sshd && chmod 0755 /var/run/sshd

ENTRYPOINT ["/usr/local/bin/keeper-entrypoint.sh"]
