FROM sorintlab/stolon:v0.6.0-pg9.6

ARG pubkey
ARG privkey

COPY $pubkey /root/.ssh/authorized_keys
COPY $privkey /root/.ssh/
RUN chmod 400 /root/.ssh/*

ENV STPROXY_CLUSTER_NAME=stolon-cluster \
    STPROXY_STORE_BACKEND=etcd \
    STPROXY_STORE_ENDPOINTS=http://localhost:2379 \
    STPROXY_LISTEN_ADDRESS=0.0.0.0 \
    STPROXY_PORT=25432

COPY bin/proxy-entrypoint.sh /usr/local/bin/
RUN chmod 777 /usr/local/bin/proxy-entrypoint.sh

RUN apt-get update && apt-get install -y bash curl gawk locales-all netcat-openbsd rsync ssh sudo && \
    chsh -s /bin/bash && mkdir /var/run/sshd && chmod 0755 /var/run/sshd

ENTRYPOINT ["/usr/local/bin/proxy-entrypoint.sh"]
